### ISSUE TITLE
User Auth not working

### ISSUE THREAD

**Issue by Kenilik** [cham11ng/sbadmin-laravel#1]
Hi, sorry if this is the wrong place to ask but I'm a bit of a noob to Laravel & git etc...

I have installed this theme and it looks really nice for a simple project I'm working on.

However, I just cannot get the authentication working. I follow all of the install instructions, I set up a mysql db and run the migrations. When I navigate to the login page and press submit I receive a MethodNotAllowedHttpException.

Am I missing something? Is the user authentication supposed to work in this port of the bootstrap to theme to laravel?

Any help getting it going would be appreciated.

**Comment by cham11ng** [comment]
Well it's not actually an issue,

This repository is just a sbadmin html theme converted into organized separate blade so here Authentication scaffolding is not generated.

what you are looking for it is https://laravel.com/docs/5.5/authentication#introduction <---- here
`php artisan make:auth` will solve your problem.
